config/routes.rb
Subscribem::Engine.routes.draw do
  root 'dashboard#index'
  get '/signup', to: 'accounts#new', as: :sign_up
  resources :accounts, only: [:create]
end

app/models/subscribem/account.rb
module Subscribem
  class Account < ActiveRecord::Base
    EXCLUDED_SUBDOMAIN = %w(admin)
    before_validation { self.subdomain == subdomain.to_s.downcase }

    validates :subdomain, presence: true,
      uniqueness: true,
      exclusion: { in: EXCLUDED_SUBDOMAIN, message: 'is not allowed, Please choose another subdomain.' },
      format: { with: /\A[\w\-]+\Z/i, message: 'is not allowed, Please choose another subdomain.' }

    belongs_to :owner, class_name: 'Subscribem::User'
    accepts_nested_attributes_for :owner
  end
end

app/models/subscribem/user.rb
module Subscribem
  class User < ActiveRecord::Base
    has_secure_password
  end
end

app/controllers/subscribem/accounts_controller.rb
module Subscribem
  class AccountsController < ApplicationController
    def new
      @account = Subscribem::Account.new
      @account.build_owner
    end

    def create
      @account = Subscribem::Account.new(account_params)
      if @account.save
        env["warden"].set_user(@account.owner, scope: :user)
        env["warden"].set_user(@account, scope: :account)
        redirect_to subscribem.root_url(subdomain: @account.subdomain)
      else
        flash[:error] = 'Sorry, your account could not be created.'
        render :new
      end
    end

    private

    def account_params
      params.require(:account).permit(:name, :subdomain, { owner_attributes: [
        :email, :password, :password_confirmation
      ]})
    end
  end
end

app/controllers/subscribem/application_controller.rb
module Subscribem
  class ApplicationController < ActionController::Base
    helper_method :current_account, :current_user, :user_signed_in?

    protected

    def current_account
      @current_account ||= begin
        account_id = env["warden"].user(scope: :account)
        Subscribem::Account.find(account_id)
      end
    end

    def current_user
      if user_signed_in?
        @current_user ||= begin
          user_id = env["warden"].user(scope: :user)
          Subscribem::User.find(user_id)
        end
      end
    end

    def user_signed_in?
      env["warden"].authenticated?(:user)
    end
  end
end

app/controllers/subscribem/dashboard_controller.rb
module Subscribem
  class DashboardController < ApplicationController
    def index
    end
  end
end

app/helpers/subscribem/application_helper.rb
module Subscribem
  module ApplicationHelper
  end
end

app/views/layouts/subscribem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribem</title>
  <%= stylesheet_link_tag    "subscribem/application", media: "all" %>
  <%= javascript_include_tag "subscribem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="flash <%= key %>"%><%= value %></div>
<% end %>

<% if user_signed_in? %>
  Signed in as <%= current_user.email %>
<% end %>

<%= yield %>

</body>
</html>

app/views/subscribem/accounts/new.html.erb
<%= form_for @account do |account| %>
  <%= account.error_messages %>

  <p>
    <%= account.label :name %><br />
    <%= account.text_field :name %>
  </p>

  <p>
    <%= account.label :subdomain %><br />
    <%= account.text_field :subdomain %>
  </p>

  <%= account.fields_for :owner do |owner| %>
    <p>
      <%= owner.label :email %><br />
      <%= owner.email_field :email %>
    </p>

    <p>
      <%= owner.label :password %><br />
      <%= owner.password_field :password %>
    </p>

    <p>
      <%= owner.label :password_confirmation %><br />
      <%= owner.password_field :password_confirmation %>
    </p>
  <% end %>

  <%= account.submit 'Create Account' %>
<% end %>

app/views/subscribem/dashboard/index.html.erb
<%= link_to 'Account Sign Up', sign_up_path %>